### ISSUE TITLE
Missing CPU/Memory usage graphs in dashboard

### ISSUE THREAD

**Issue by blockloop** [kz8s/tack#129]
I just switched to tack from kube-aws and I noticed that the dashboard does not have the CPU and Memory usage graphs as seen here

![image](https://cloud.githubusercontent.com/assets/3022496/21834738/50bb6b78-d77d-11e6-8d13-fd59fab6c2f9.png)

The [kubernetes blog says](http://blog.kubernetes.io/2016/10/Production-Kubernetes-Dashboard-UI-1.4-improvements_3.html) that this feature was added in k8s v1.4. I opened the chrome debugger and noticed that `cumulativeMetrics` for all requests returns an empty array. I'm using the dashboard  UI with `kube proxy`.

![image](https://cloud.githubusercontent.com/assets/3022496/21834819/d8c5e598-d77d-11e6-8921-0b2960412bd6.png)

**Comment by owenmorgan** [comment]
You'll need to deploy heapster into your cluster

**Comment by blockloop** [comment]
Ah. Thanks. What do you think about including this in tack?

**Comment by blockloop** [comment]
If anybody else lands here via search here is the configuration I used to get heapster working.

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster:v1.3.0-beta.0
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default

---
apiVersion: extensions/v1beta1
kind: Service
apiVersion: v1
metadata:
  name: heapster
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Heapster"
    k8s-app: heapster
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    k8s-app: heapster
```
