### ISSUE TITLE
No default storage provisioner

### ISSUE THREAD

**Issue by lukeab** [kz8s/tack#173]
When i setup my tack cluster in amazon, the first thing i wanted to do was run jenkins from a helm chart. The stable/jenkins chart requires a PV available for use with it's PVC. 
I solved this by adding this `awsstandardstorageand.yaml` applying it to my setup:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-1a
```
Since this is an "opinionated" tool for setting up a k8s cluster, tack should provide a standard storage option, out of the box.
