### ISSUE TITLE
ELB's?  Clarification

### ISSUE THREAD

**Issue by bkosick** [kz8s/tack#186]
Hey Guys,

Sorry to be a bother, but could someone please clarify the subnet tagging part if this setup.   Basically, I checked out tack did a make all, was happy and am working on a service that *should* according to my research, setup an ELB automagically when running an AWS kubernetes cluster.

After some additional reading, I found this linked to from your README, but Im afraid that I dont quite understand/grok it yet.

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#66 

Here's my service file:  
```
---
apiVersion: v1
kind: Service
metadata:
  # Expose the management HTTP port on each node
  name: myapp-ui
  labels:
    app: myapp-ui
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: myapp-ui
  type: LoadBalancer
```
```
kubectl describe svc myapp-ui
Name:			myapp-ui
Namespace:		default
Labels:			app=myapp-ui
Annotations:		<none>
Selector:		app=myapp-ui
Type:			LoadBalancer
IP:			10.3.0.225
Port:			http	80/TCP
NodePort:		http	30915/TCP
Endpoints:		10.2.102.10:80
Session Affinity:	None
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason				Message
  ---------	--------	-----	----			-------------	--------	------				-------
  2d		2m		777	service-controller			Normal		CreatingLoadBalancer		Creating load balancer
  2d		2m		768	service-controller			Warning		CreatingLoadBalancerFailed	(events with common reason combined)```
Any explanation, help would be appreciated.

Thanks
