### ISSUE TITLE
LoadBalancer pending forever

### ISSUE THREAD

**Issue by guiocavalcanti** [kz8s/tack#73]
Hey, I just deployed a k8s cluster from master and tried to create a LoadBalancer Service [1]. The external IP (elb) isn't provisioned and hangs forever:

```
k get svc ads-ops
NAME      CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
ads-ops   10.3.0.206   <pending>     80/TCP    31s
```

[1]

``` yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ads-ops
  name: ads-ops
  namespace: ads-ops-staging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9292
  selector:
    run: ads-ops
  sessionAffinity: None
  type: LoadBalancer
```
